In [2]:
import pandas as pd

In [3]:
s = pd.Series([10,20,30])

In [4]:
s

0    10
1    20
2    30
dtype: int64

In [5]:
d = pd.DataFrame({
    "name":["Dhruvi","Hasti","Vruti"],
    "Age":[20,19,21],
    "batch":["B","A","A"]})

In [6]:
d

     name  Age batch
0  Dhruvi   20     B
1   Hasti   19     A
2   Vruti   21     A

In [7]:
df = pd.read_csv("employee.csv")

### Data Selection

In [8]:
df["Department"].head()

0                     Sales
1    Research & Development
2    Research & Development
3    Research & Development
4    Research & Development
Name: Department, dtype: str

In [10]:
df[["Age", "Department", "MonthlyIncome"]].head()

   Age              Department  MonthlyIncome
0   41                   Sales           5993
1   49  Research & Development           5130
2   37  Research & Development           2090
3   33  Research & Development           2909
4   27  Research & Development           3468

### Data Filtering

In [12]:
df[df["Age"] > 40].head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
6,59,No,Travel_Rarely,1324,Research & Development,3,3,Medical,1,10,...,1,80,3,12,3,2,1,0,0,0
18,53,No,Travel_Rarely,1219,Sales,2,4,Life Sciences,1,23,...,3,80,0,31,3,3,25,8,3,7
25,53,No,Travel_Rarely,1282,Research & Development,5,3,Other,1,32,...,4,80,1,26,3,2,14,13,4,8

### Grouping

In [13]:
df.groupby("Department")["MonthlyIncome"].mean()

Department
Human Resources           6654.507937
Research & Development    6281.252862
Sales                     6959.172646
Name: MonthlyIncome, dtype: float64

### Aggregation

In [14]:
df.groupby("Department")["MonthlyIncome"].agg("mean")

Department
Human Resources           6654.507937
Research & Development    6281.252862
Sales                     6959.172646
Name: MonthlyIncome, dtype: float64